#! /bin/sh

bspc monitor HDMI-0 -d I-A I-B I-C I-D I-E Music Audio-A Audio-B Audio-C
bspc monitor DVI-I-1 -d II-A II-B II-C II-D II-E Games

bspc config border_width         6
bspc config window_gap          20

bspc config split_ratio      	0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	false
bspc config click_to_focus	true
 
bspc config external_rules_command  $HOME/.config/bspwm/external_rules

## My Colours ##
bspc config active_border_color	 	'#0A0A0A'
bspc config focused_border_color 	'#C5C8C6'
bspc config normal_border_color		'#0A0A0A'
bspc config presel_border_color		'#5f819d'
bspc config urgent_border_color		'#a54252'




source "$HOME/.start-bspwm"
